### ISSUE TITLE
[fix] CSSのu-dbのサンプルコードの修正

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#15]
``` html
<p><code>$-md</code>以降になると、<span class="u-db-md">ここから改行されます。</span></p>
```

ではなく、

``` html
<p><code>-md</code>以降になると、<span class="u-db-md"></span>ここから改行されます。</p>
```

spanの中にテキストを入れる必要はない。brのようにタグ単体で指定した方がわかりやすい。
u-dbはテキストを囲まないと改行をコントロールできない。

**Comment by manabuyasuda** [comment]
以下のようにしても改行をコントロールできる。

``` css
.br:before {
  content: "\A";
  white-space: pre;
}
```

でも、spanタグを使って改行させる場合はdisplayプロパティを使った方が直感的でわかりやすい。
