### ISSUE TITLE
[add] c-inlineコンポーネントの追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#16]
dl要素をインラインで表示するコンポーネント。

``` scss
.c-inline {
  font-size: 0;
}

.c-inline__start,
.c-inline__end {
  display: inline;
  font-size: medium;
  font-size: 1rem;
}

.c-inline__start:not(:first-child):before {
  content: "\A";
  white-space: pre;
}
```

c-inline__start直前で改行される。
