### ISSUE TITLE
[add] 括弧付き昇順リスト

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#28]
``` scss
.c-list-brackets {
  display: table;
  @include _c-list-unstyled();
}

.c-list-brackets__item {
  display: table-row;
  counter-increment: brackets;
  &:before {
    content: "(" counter(brackets) ")";
    display: table-cell;
    padding-right: 0.5em;
    text-align: right;
  }
}
```

``` jade
ol.c-list-brackets
  li.c-list-brackets__item リストリストリストリストリストリストリストリストリストリストリストリストリストリストリストリスト
  li.c-list-brackets__item リスト
  li.c-list-brackets__item リスト
```

(1)  リスト
(2)  リスト

のようなリストスタイルになる。
