### ISSUE TITLE
[add] 注釈リストの追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#29]
``` scss
.c-list-notes {
  display: table;
  @include _c-list-unstyled();
}

.c-list-notes__item {
  display: table-row;
  &:before {
    display: table-cell;
  }
  [lang="ja"] &:before {
    content: "※";
  }
  [lang="en_US"] &:before {
    content: "*";
  }
}
```

注釈に使う記号は日本語では※（米印）、英語では*（アスタリスク）になる。※1のような書き方は文脈に依存するため、あらかじめ用意しないほうが汎用的に使える。
