### ISSUE TITLE
[update] .c-list-markと.p-iconの見直し

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#30]
.c-list-markと.p-iconを併用したときにテキストで左揃えができていない。
-  .c-list-markを.p-iconより後に読み込む必要がある。
- .p-iconは:beforeで表示するほうが影響範囲が狭い
- .c-list-markの余白まわりをリセットして、余白ありとなしのパターンを作る

``` scss
@mixin _c-list-mark() {
  display: table;
  @include _c-list-unstyled();
}

@mixin _c-list-mark__item() {
  display: table-row;
}

@mixin _c-list-mark__icon() {
  display: table-cell;
}

@mixin _c-list-mark__items() {
  @include _c-list-unstyled();
}
```

``` scss
/* ul */
.c-list-mark {
  @include _c-list-mark();
}

/* ul > li */
.c-list-mark__item {
  @include _c-list-mark__item();
}

/* li > span */
.c-list-mark__icon {
  @include _c-list-mark__icon();
}

.c-list-mark__iconleft {
  @include _c-list-mark__icon();
  padding-right: 0.5em;
}

/* li > ul */
.c-list-mark__items {
  @include _c-list-mark__items();
  margin-left: 1em;
}
```

アイコンをテキストの右側にもってくるパターンは、この構造では無理。単純にテキストの右側にspanをつけるのが妥当。このパターンはアイコンをつけて、なおかつテキストで左揃えする場合に使う。
