### ISSUE TITLE
[add] c-list-inlineコンポーネントの追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#34]
``` scss
.c-list-inline {
  display: block;
  margin: 0;
  padding: 0;
  font-size: 0;
  list-style-type: none;
}

.c-list-inline__item {
  display: inline-block;
  font-size: medium;
  font-size: 1rem;
  vertical-align: top;
}

.c-list-inline--medium {
  > .c-list-inline__item:not(:last-child) {
    margin-right: 1em;
  }
}

@include _responsive('.c-list-inline--left') {
  text-align: left;
}

@include _responsive('.c-list-inline--center') {
  text-align: center;
}

@include _responsive('.c-list-inline--right') {
  text-align: right;
}
```

リスト1　リスト2　リスト3
のようなレイアウトになる。

`.c-list-inline--medium`を指定すると余白で区切られる。
