### ISSUE TITLE
[add] figureとfigcaptionのようなキャプションコンポーネントを追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#41]
``` scss
.p-figure {
}

.p-figure__image {

}

.p-figure__caption-top {
  margin-bottom: 0.5em;
}

.p-figure__caption-bottom {
  margin-top: 0.5em;
}
```
