### ISSUE TITLE
[add] 文字間を調節する汎用クラスを追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#42]
「社名」を「社　名」のように表示させたいときに使う。

``` scss
/**
 * 文字の右側に1文字分の余白をあけます。
 * `<span class="u-text-spacing-full">社</span>名` => `社　名`
 */
.u-text-spacing-full {
  letter-spacing: 1em;
}

/**
 * 文字の右側に0.5文字分の余白をあけます。
 * `<span class="u-text-spacing-half">社</span>名` => `社 名`
 */
.u-text-spacing-half {
  letter-spacing: 0.5em;
}
```
