### ISSUE TITLE
[add] 余白を管理するScopeレイヤーとUtilityレイヤーの作成

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#49]
現状ではセクションやコンポーネントごとに余白の管理をしている。
ただし、これだとマークアップが煩雑になる。

ScopeレイヤーとUtilityレイヤーで一括管理できる仕組みを作る。
例えば以下のようにセクションの余白とBEMでいうBlockとElementが内包している要素に一律で指定する余白を管理する。

``` scss
.u-section {
  margin-bottom: 48px;
}

.s-element {
  > * {
    margin-bottom: 24px;
  }
  > *:last-child {
    margin-bottom: 0;
  }
}

.s-block {
  > * {
    margin-bottom: 36px;
  }
  > *:last-child {
    margin-bottom: 0;
  }
}
```

``` jade
  div.u-section
    div.s-block
      div.c-flag
        div.c-flag__image
          img(src="http://lorempixel.com/150/150/")
        div.c-flag__body.s-element
          p.u-mb-medium 画像とテキストを横並びにするオブジェクトです。余白サイズ、垂直方向、要素の配置順の反転の指定ができます。
          p 画像とテキストを横並びにするオブジェクトです。余白サイズ、垂直方向、要素の配置順の反転の指定ができます。

      div.c-flag
        div.c-flag__image
          img(src="http://lorempixel.com/150/150/")
        div.c-flag__body.s-element
          p 画像とテキストを横並びにするオブジェクトです。余白サイズ、垂直方向、要素の配置順の反転の指定ができます。
          p 画像とテキストを横並びにするオブジェクトです。余白サイズ、垂直方向、要素の配置順の反転の指定ができます。
```

**Comment by manabuyasuda** [comment]
Scopeレイヤーでは

``` scss
.s-block {
  > {
    div,a,
    h1, h2, h3, h4, h5, h6,
    ul, ol, dl,
    blockquote, p, address,
    table,
    fieldset, figure,
    pre {
      &:not(:last-child) {
        margin-bottom: 1.7rem;
      }
    }
  }
}
```

のように指定。以下のようにコンパイルされる。

``` css
.s-block > div:not(:last-child),
.s-block > a:not(:last-child),
.s-block > h1:not(:last-child),
.s-block > h2:not(:last-child),
.s-block > h3:not(:last-child),
.s-block > h4:not(:last-child),
.s-block > h5:not(:last-child),
.s-block > h6:not(:last-child),
.s-block > ul:not(:last-child),
.s-block > ol:not(:last-child),
.s-block > dl:not(:last-child),
.s-block > blockquote:not(:last-child),
.s-block > p:not(:last-child),
.s-block > address:not(:last-child),
.s-block > table:not(:last-child),
.s-block > fieldset:not(:last-child),
.s-block > figure:not(:last-child),
.s-block > pre:not(:last-child) {
  margin-bottom: 1.7rem;
}
```
