### ISSUE TITLE
[update] .p-figureのコードを整理する

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#60]
``` scss
.p-figure__caption-top {
  display: table-caption;
  caption-side: top;
}

.p-figure__caption-bottom {
  display: table-caption;
  caption-side: bottom;
}

.p-figure__caption-top,
.p-figure__caption-bottom {
  font-size: 0.8rem;
}
```

は

``` scss
.p-figure__caption-top {
  caption-side: top;
}

.p-figure__caption-bottom {
  caption-side: bottom;
}

.p-figure__caption-top,
.p-figure__caption-bottom {
  display: table-caption;
  font-size: 0.8rem;
}
```

とするほうが見通しがいい。
