### ISSUE TITLE
[update] 文字サイズの拡大に対応

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/prompt#64]
拡大機能はIE9以上であれば対応の必要はない（pxでも拡大できるようになったため）。

ただし、文字サイズだけの拡大はpxで指定していると機能しない。
ルート要素に%で指定することで解決する。IEとEdgeでも確認ずみ。

```css
html {
  font-size: 100%;
}
```
